name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-check:
    uses: ngjocelyn/ssd-lab08/.github/workflows/dependency-check.yml@main
    permissions:
      contents: read

  lint:
    needs: dependency-check
    uses: ngjocelyn/ssd-lab08/.github/workflows/lint.yml@main
    permissions:
      contents: read

  codeql:
    needs: dependency-check
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      packages: read
      security-events: write
      contents: read

  tests:
    needs: [lint, codeql]
    uses: ngjocelyn/ssd-lab08/.github/workflows/test.yml@main
    permissions:
      contents: read