name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-check:
    uses: ngjocelyn/ssd-lab08/.github/workflows/dependency-check.yml@main

  lint:
    needs: dependency-check
    uses: ngjocelyn/ssd-lab08/.github/workflows/lint.yml@main

  codeql:
    needs: dependency-check
    uses: ./.github/workflows/codeql.yml
    permissions:
      contents: read
      pull-requests: write

  tests:
    needs: [lint, codeql]
    uses: ngjocelyn/ssd-lab08/.github/workflows/test.yml@main
