name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MyReactApp"
          path: "./"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: Dependency-Check-Report
          path: dependency-check-report

      # Lint JavaScript
      - name: Run ESLint
        uses: sibiraj-s/action-eslint@v4
        with:
          eslint-args: "--ignore-path=.gitignore --quiet"
          extensions: "js,jsx,ts,tsx"
          annotations: true

      # Start App in Background
      - name: Start Application
        run: npm start &
        env:
          CI: true

      # Wait for App to Be Ready
      - name: Wait for HTTP Service
        run: |
          sleep 10
          curl -f http://localhost:3000 || exit 1

      # Install and Run Selenium Tests
      - name: Set up Chrome and Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxss1 libappindicator3-1 libasound2
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          npm install selenium-webdriver

      - name: Run Selenium Tests
        run: node tests/seleniumTest.js

      # 🧪 6. Run Integration Tests
      - name: Run Integration Test Suite
        run: npm test
